language: haskell

ghc:
 - '7.10'
 - 7.8
# - 7.6 classify gives a stack overflow
# - 7.4 weird error with fmap
# - '7.10' not supported by travis-ci yet

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libjudy-dev

script:
  - test/test.sh
